name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Oslo
          repositories_forks: no
          plugin_languages: yes
          plugin_followup: no
          plugin_habits: no
          plugin_lines: no
          plugin_traffic: no
          plugin_habits_charts: no
          plugin_habits_facts: no
          plugin_stargazers: no
          plugin_achievements: no
          plugin_achievements_threshold: A
          plugin_achievements_secrets: no
          plugin_achievements_limit: 0
          
          plugin_languages_skipped: conan-center-index
          plugin_projects: no
          plugin_isocalendar: no
